### PR TITLE
DM-37786-v25: backport hooks for tasks to set dataset-query-constraint defaults

### PR DESCRIPTION
**Pull request by TallJimbo**
## Checklist

- [x] ran Jenkins
- [x] added a release note for user-visible changes to `doc/changes`

### CODE REVIEW

**Comment by TallJimbo** [comment]
Since this is a backport and Jenkins has succeeded, I'm going to ignore the CI failures here; those seem to be due to a newer Python stack or are otherwise unrelated to these changes, and `v25` is not trying to keep up with bleeding edge the same way `main` is.

**Comment by timj** [comment]
I'm actually confused how it managed much at all since it installed sqlalchemy2.

**Comment by timj** [comment]
@TallJimbo I don't think we can leave this branch in a failing state -- the build tests must pass before the PyPI uploads are completed so if we want the 25.0.0 release to appear on PyPI (I would suggest that we do) we have to make sure the tests pass. This would likely involve at least pinning sqlalchemy to <2.  

I'm not sure why the open-files failures are triggering now but the fix is to add an `open_files_ignore` section to the `pyproject.toml` as we do in `daf_butler`.

**Comment by timj** [comment]
We probably also on this branch want to restrict the versions of dependencies we define in pyproject.toml to be `>24, <25.2000` and change the requirements.txt to point at 25.0.x branches of dependencies for the builds.

**Comment by TallJimbo** [comment]
Sounds like we need to consider this part of including middleware in point releases (as well as v25, when it actually goes out for the first time, of course).

**Comment by timj** [comment]
I'll have to add all the release notes to the 25 branch so I'll fix things up then.

**Pull request merged**
