### PR TITLE
DM-15220: Move SuperTask class here from pipe_supertask

### PR DESCRIPTION
**Pull request by andy-slac**
SuperTask has new name now, from now on it is to be called
PipelineTask, grepping for "super" should only find calls to super()
method. Configuration classes for PipelineTaks were moved here too (in
config module).

Note that this cannot be merged until we have `daf_butler` included in `lsst_distrib` (which should happen ~soon).

### CODE REVIEW

**Comment by timj** [comment]
@andy-slac I think you can merge this any time you get it reviewed. If pipe_base now depends on daf_butler then daf_butler will be pulled in automatically. We don't want to put daf_butler into lsst_distrib on its own if pipe_base already pulls it in.

**Comment by timj** [comment]
Although I don't see any diff for the table file to pull in daf_butler.

**Comment by andy-slac** [comment]
My fault, thanks for starting the review :smiley: I'll fix table file.

**Comment by timj** [comment]
I would have preferred the history was retained during the transfer. I think `git format-patch` and `git am` could have worked.

**Comment by andy-slac** [comment]
Let me see if I can bring that back. pipe_supertask history was itself very messy, not sure if anyone would want to see that.

**Comment by andy-slac** [comment]
@timj, do you like https://github.com/lsst/pipe_base/compare/tickets/DM-15220-1 better? If yes then I'll switch that branch for this one.

**Comment by timj** [comment]
The new branch looks okay to me from a quick glance.

**Comment by andy-slac** [comment]
OK, now all history is here too.

**Pull request merged**
