### PR TITLE
DM-20376: Correct exit status

### PR DESCRIPTION
**Pull request by timj**

### CODE REVIEW

**Comment by kfindeisen** [comment]
Please make sure this PR also updates the [Sphinx documentation on status codes](https://pipelines.lsst.io/modules/lsst.pipe.base/command-line-task-argument-reference.html#status-code) (in particular, the cap of 127).

**Comment by ktlim** [comment]
Do you think I should increase that to 255?  Traditionally 128-255 has been reserved for signal-caused exits, but I can imagine we would like to have, for example, 189 (CCDs in focal plane) available.
255 is a hard limit, of course.  I guess there should also be at least a log message if we exceed whatever cap there is.

**Comment by andy-slac** [comment]
Exit codes above 127 are still interpreted as "exited due to signal". It may confuse users if parent process says "child was killed by signal 61 (core dumped)".

**Comment by timj** [comment]
@ktlim are we abandoning this branch?  It's gen2-specific. @andy-slac is there an equivalent case in pipetask?

**Comment by andy-slac** [comment]
@timj, I _believe_ pipetask should exit with non-zero code on any error. Proving that may be as hard as solving halting problem 🙂

**Comment by timj** [comment]
Are we going to try to merge this or are we going to close it and the associated Jira ticket?

**Comment by timj** [comment]
The CmdLineTask code no longer exists.

**Pull request closed without merging**
